// ISO 639-1 language codes with their display names
export const LANGUAGE_MAP = new Map([
  ["en", "English"],
  ["es", "Spanish"],
  ["fr", "French"],
  ["de", "German"],
  ["it", "Italian"],
  ["pt", "Portuguese"],
  ["ru", "Russian"],
  ["ja", "Japanese"],
  ["ko", "Korean"],
  ["zh", "Chinese"],
  ["ar", "Arabic"],
  ["hi", "Hindi"],
  ["tr", "Turkish"],
  ["pl", "Polish"],
  ["nl", "Dutch"],
  ["sv", "Swedish"],
  ["da", "Danish"],
  ["no", "Norwegian"],
  ["fi", "Finnish"],
  ["cs", "Czech"],
  ["hu", "Hungarian"],
  ["ro", "Romanian"],
  ["bg", "Bulgarian"],
  ["hr", "Croatian"],
  ["sk", "Slovak"],
  ["sl", "Slovenian"],
  ["et", "Estonian"],
  ["lv", "Latvian"],
  ["lt", "Lithuanian"],
  ["el", "Greek"],
  ["he", "Hebrew"],
  ["th", "Thai"],
  ["vi", "Vietnamese"],
  ["id", "Indonesian"],
  ["ms", "Malay"],
  ["tl", "Filipino"],
  ["uk", "Ukrainian"],
  ["be", "Belarusian"],
  ["ka", "Georgian"],
  ["hy", "Armenian"],
  ["az", "Azerbaijani"],
  ["kk", "Kazakh"],
  ["ky", "Kyrgyz"],
  ["uz", "Uzbek"],
  ["mn", "Mongolian"],
  ["ne", "Nepali"],
  ["si", "Sinhala"],
  ["my", "Burmese"],
  ["km", "Khmer"],
  ["lo", "Lao"],
  ["is", "Icelandic"],
  ["mt", "Maltese"],
  ["ga", "Irish"],
  ["cy", "Welsh"],
  ["eu", "Basque"],
  ["ca", "Catalan"],
  ["gl", "Galician"],
  ["af", "Afrikaans"],
  ["sw", "Swahili"],
  ["am", "Amharic"],
  ["or", "Odia"],
  ["bn", "Bengali"],
  ["gu", "Gujarati"],
  ["kn", "Kannada"],
  ["ml", "Malayalam"],
  ["mr", "Marathi"],
  ["pa", "Punjabi"],
  ["ta", "Tamil"],
  ["te", "Telugu"],
  ["ur", "Urdu"],
  ["fa", "Persian"],
  ["ps", "Pashto"],
  ["sd", "Sindhi"],
]);

export const VALID_LANGUAGE_CODES = new Set(LANGUAGE_MAP.keys());

// Helper function to get language name from code
export const getLanguageName = (code: string): string => {
  return LANGUAGE_MAP.get(code.toLowerCase()) || code.toUpperCase();
};
